# fly.toml app configuration file generated for coordinatorserver on 2025-11-18T19:11:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coordinatorserver'
primary_region = 'lax'

[build]

[http_service]
internal_port = 3000
force_https = true
# Prevent Fly from auto-stopping machines due to perceived excess capacity.
# This keeps at least one machine running so clients can connect to your server.
auto_stop_machines = "off"
auto_start_machines = true
# Ensure at least one machine stays up.
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
